# Generated by Django 2.2.7 on 2019-11-07 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cadastro', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Aluguel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_retirada', models.DateField()),
                ('data_devolucao', models.DateField(blank=True, null=True)),
                ('roupa', models.ForeignKey(on_delete='CASCADE', to='cadastro.Roupa')),
                ('valor', models.ForeignKey(on_delete='CASCADE', to='cadastro.Valor')),
            ],
        ),
    ]
